services:
  redis-cache:
    image: redis:8.4.0-alpine
    command: [ "sh", "-c", "redis-server /usr/local/etc/redis/redis.conf --requirepass \"$REDIS_PASSWORD\"" ]
    volumes:
      - ./infra/redis/cache/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./redis-data:/data
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a \"$${REDIS_PASSWORD}\" ping | grep PONG" ]
      interval: 5s
      timeout: 5s
      retries: 3

  postgres:
    image: postgres:16-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      redis-cache:
        condition: service_healthy
      postgres:
        condition: service_healthy

volumes:
  pgdata:
