services:
  redis-cache:
    env_file:
      - .env.local
    ports:
      - "${REDIS_HOST_PORT:-6379}:6379"
  redis-cache-ui:
    image: redis/redisinsight:3.0
    container_name: redis-cache-ui
    ports:
      - "15540:5540"
    volumes:
      - redisinsight-data:/db
    depends_on:
      - redis-cache
  postgres:
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env.local
    ports:
      - "${POSTGRES_HOST_PORT:-5432}:5432"

  app:
    env_file:
      - .env.local
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      REDIS_HOST: redis-cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "${APP_HOST_PORT}:8080"
    volumes:
      - ./logs:/app/logs

volumes:
  redisinsight-data: